version: "3.9"

services:
  emprestimo-agora-db:
    image: postgres:15-alpine
    container_name: emprestimo-agora-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: emprestimoagora
    ports:
      - "5432:5432"
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${LOCAL_DB_USERNAME} -d ${LOCAL_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  app:
    build: .
    container_name: api-emprestimo-agora
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      emprestimo-agora-db:
        condition: service_healthy
    networks:
      - backend

networks:
  backend:
    driver: bridge
