-- Script SQL para ambiente de desenvolvimento com PostgreSQL
-- Inserção de dados de exemplo com proteção contra duplicatas

-- Inserção dos dados de exemplo usando ON CONFLICT para evitar duplicatas
INSERT INTO PRODUTO (CO_PRODUTO, NO_PRODUTO, PC_TAXA_JUROS, NU_MINIMO_MESES, NU_MAXIMO_MESES, VR_MINIMO, VR_MAXIMO) 
VALUES (1, 'Empréstimo Pessoal Básico', 0.017900000, 0, 24, 200.00, 10000.00)
ON CONFLICT (CO_PRODUTO) DO NOTHING;

INSERT INTO PRODUTO (CO_PRODUTO, NO_PRODUTO, PC_TAXA_JUROS, NU_MINIMO_MESES, NU_MAXIMO_MESES, VR_MINIMO, VR_MAXIMO) 
VALUES (2, 'Empréstimo Pessoal Intermediário', 0.017500000, 25, 48, 10001.00, 100000.00)
ON CONFLICT (CO_PRODUTO) DO NOTHING;

INSERT INTO PRODUTO (CO_PRODUTO, NO_PRODUTO, PC_TAXA_JUROS, NU_MINIMO_MESES, NU_MAXIMO_MESES, VR_MINIMO, VR_MAXIMO) 
VALUES (3, 'Empréstimo Pessoal Premium', 0.018200000, 49, 96, 100000.01, 1000000.00)
ON CONFLICT (CO_PRODUTO) DO NOTHING;

INSERT INTO PRODUTO (CO_PRODUTO, NO_PRODUTO, PC_TAXA_JUROS, NU_MINIMO_MESES, NU_MAXIMO_MESES, VR_MINIMO, VR_MAXIMO) 
VALUES (4, 'Empréstimo Empresarial', 0.015100000, 96, NULL, 1000000.01, 10000000.00)
ON CONFLICT (CO_PRODUTO) DO NOTHING;

-- Verificação dos dados inseridos
-- SELECT * FROM PRODUTO ORDER BY CO_PRODUTO;